# Generated by Django 4.2 on 2023-04-23 20:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0002_tag_alter_post_author_post_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="author",
        ),
    ]
