# Generated by Django 4.2 on 2023-04-22 17:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_user_bio_user_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="subscribers",
            field=models.ManyToManyField(
                related_name="subscriptions", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
