# Generated by Django 4.2 on 2023-04-22 17:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_post"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Post",
        ),
    ]
