# Generated by Django 4.2 on 2023-04-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_remove_user_bio_remove_user_profile_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(blank=True, upload_to="profile_images/"),
        ),
    ]
