# Generated by Django 4.2 on 2023-04-23 20:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0008_user_bio_user_profile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="user",
            name="profile_image",
        ),
    ]
